# Generated by Django 2.2 on 2019-05-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesToSelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notestoselfmodel',
            old_name='owner',
            new_name='author',
        ),
    ]
