# Generated by Django 2.2 on 2019-05-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesToSelfModel',
        ),
    ]
